/*
 * @BUSINESS: Utility class for slack related functionality
 * @DATE: 2024-05-02
 * @AUTHOR: Tanium Dev Team
 * @REQUEST:
 * RequestId  ModifiedDate  Comment
 * SS-7278    2024-05-02    Created the class
 * SS-8182    2024-05-13    Added CHANNEL_SC_POLAND_CASE_ROUTINGS and CHANNEL_SUPPORT_CENTER_TICKETS_POLAND
 */
public with sharing class SlackUtility {
	public static String CHANNEL_FED_CASE = 'C014RR8QBCM';
	public static String CHANNEL_SUPPORT_CENTER_TICKETS = 'C01DAP85W3A';
	public static String CHANNEL_SUPPORT_CENTER_JAPAN = 'C041FV8TT7U';
	public static String CHANNEL_TRIAGE_TICKETS = 'C0L7DC8Q6';
	public static String CHANNEL_COMMUNIYY = 'C7QQE7H32';
	public static String CHANNEL_SC_POLAND_CASE_ROUTING = 'C0707MJL13P';
	public static String CHANNEL_SUPPORT_CENTER_TICKETS_POLAND = 'C05GB6MNGP2';
	public static String CHANNEL_ROSCO_DEBUG = 'CCC66LTRT'; // UAT
}