/*
 * Licensed Materials - Property of IBM
 * 6949-83K
 * © Copyright IBM Corp. 2022 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

public without sharing class x7sMembersTestConstants {
	// Profiles
	public static final String COMPANY_COMMUNITY_PROFILE_NAME = 'Customer Community User';
	public static final String PARTNER_COMMUNITY_PROFILE_NAME = 'Partner Community User';

	//	Topics
	public static final Integer TEST_TOPIC_COUNT = 3;

	// Test NetworkId
	public final static String TEST_COMMUNITY_ID = '0DB0e000000CaezGAC';
}